from __future__ import annotations
from typing import Any, Optional, Protocol

class Storage(Protocol):
    def write_json(self, key: str, payload: Any) -> str: ...
    def read_json(self, key: str) -> Optional[Any]: ...
    def delete(self, key: str) -> None: ...